### PR TITLE
Rename `okta-hosted-login` folder to `federated-okta-hosted`

### PR DESCRIPTION
**Pull request by arvindkrishnakumar-okta**
**Issue:**

OKTA-375899

**What is done?**

Renamed `okta-hosted-login` folder to `federated-okta-hosted` per [this](https://oktawiki.atlassian.net/wiki/spaces/eng/pages/1863198336/Direct+Auth+SDK+Project+-+Requirements#Sample-Description).

### CODE REVIEW

**Review by laura-rodriguez — APPROVED** [review]
LGTM. We might need to update the readme with OIE details.

**Comment by arvindkrishnakumar-okta** [comment]
> LGTM. We might need to update the readme with OIE details.

Made few updates per discussion with the team.

**Review by laura-rodriguez — APPROVED** [review]

**Comment by vijetmahabaleshwar-okta** [comment]
Are you planning to rename `custom-login` to `self-hosted` in a separate PR?

**Comment by mraible** [comment]
`federated-okta-hosted` is a terrible name and sounds like it was created by people that write authentication specs. I vote we change it to `easiest-login`. 😃

**Comment by bdemers** [comment]
Agreed, I think it also sounds enterprisie, it's not something I think I'd click on when looking for an example of out add auth to my application.  Along the lines of what @mraible suggested, maybe `standard-login` or something like that, IMHO we want to give the impression that the `okta-hosted-login` is the default choice.

cc: @jefftaylor-okta

**Pull request closed without merging**
